#!/bin/perl
# conf - minimal config file editor; no dependencies, works on very old Perls
use strict;
use warnings;

## GLOBALS
use Env qw( HOME );
my %CONFIGS = (
  tmux => "$HOME/.tmux.conf",
  vim  => "$HOME/.vimrc",
  zsh  => "$HOME/.zshrc",
);

sub edit (@) { system('vim', '-p', @_) }

sub files ( )
{
  return sort values %CONFIGS
    unless @ARGV;

  if (my @bad_args = grep { !$CONFIGS{$_} } @ARGV) {
   die sprintf(
      "No config files registered for:\n%s\nExiting.\n",
      sprintf("- %s\n" x @bad_args, @bad_args),
    );
  }

  return @CONFIGS{@ARGV};
}

edit files; # :^)
